package models;

import java.math.BigDecimal;
import java.time.LocalDate;

public class AbonnementAvecEngagement extends Abonnement {

    private int dureeEngagementMois;

    // ✅ Constructor for new objects (id auto-generated by base class)
    public AbonnementAvecEngagement(String nomService, BigDecimal montantMensuel,
                                    LocalDate dateDebut, LocalDate dateFin,
                                    Statut statut, int dureeEngagementMois) {
        super(nomService, montantMensuel, dateDebut, dateFin, statut);
        this.dureeEngagementMois = dureeEngagementMois;
    }

    // ✅ Constructor for objects coming from DB (id provided)
    public AbonnementAvecEngagement(String id, String nomService, BigDecimal montantMensuel,
                                    LocalDate dateDebut, LocalDate dateFin,
                                    Statut statut, int dureeEngagementMois) {
        super(id, nomService, montantMensuel, dateDebut, dateFin, statut);
        this.dureeEngagementMois = dureeEngagementMois;
    }

    public int getDureeEngagementMois() {
        return dureeEngagementMois;
    }

    public void setDureeEngagementMois(int dureeEngagementMois) {
        this.dureeEngagementMois = dureeEngagementMois;
    }

    @Override
    public String getType() {
        return "AVEC_ENGAGEMENT";
    }

    @Override
    public String toString() {
        return "AbonnementAvecEngagement{" +
                super.toString() +
                ", dureeEngagementMois=" + dureeEngagementMois +
                '}';
    }
}
